### ISSUE TITLE
failed to import

### ISSUE THREAD

**Issue by stickylab** [battleofmages/battleofmages#10]
![image](https://github.com/battleofmages/battleofmages/assets/87752832/20d9ef1f-558d-4930-a86d-45cb6441fb28)

**Comment by akyoto** [comment]
![image](https://github.com/battleofmages/battleofmages/assets/438936/1e9fd72a-d3a3-43b9-9c43-2deccaf3a93b)
![image](https://github.com/battleofmages/battleofmages/assets/438936/86fd532c-9003-4cac-ab46-55187baec4c2)
